name: Exercise multiple Java Frameworks to Azure in Multiple Ways

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
      - cron:  '0 7 * * *'
  repository_dispatch:

env:
  location: eastus
    
jobs:
  noframework:
    runs-on: ubuntu-latest
    steps:
      
      - name: Discovery
        run: |
          find . -type f -print

      - name: Java 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
          
      - name: Build noframework
        run: mvn -DskipTests clean install --file noframework/pom.xml
        
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create Resource Group
        id: create-resource-group
        run: |
          export resourceGroup=${GITHUB_RUN_ID}${GITHUB_RUN_NUMBER}
          echo ${resourceGroup} ${location}
          az group create --verbose --name ${resourceGroup} --location ${location}
          
  cleanup-noframework:
    needs: noframework
    if: always()
    runs-on: ubuntu-latest
    steps:
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Delete Resource Group
        id: delete-resource-group
        run: |
          export resourceGroup=${GITHUB_RUN_ID}${GITHUB_RUN_NUMBER}
          echo ${resourceGroup} ${location}
          az group delete --yes --no-wait --verbose --name ${resourceGroup}
