name: Exercise multiple Java Frameworks to Azure in Multiple Ways

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
      - cron:  '0 7 * * *'
  repository_dispatch:

env:
  location: eastus
    
jobs:
  noframework:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout helloworldfarm
        uses: actions/checkout@v2
        with:
          path: helloworldfarm
      
      - name: Java 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
          
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create Resource Group
        id: create-resource-group
        run: |
          export resourceGroup=${GITHUB_RUN_ID}${GITHUB_RUN_NUMBER}
          echo ${resourceGroup} ${location}
          az group create --verbose --name ${resourceGroup} --location ${location}
          
      - name: Build noframework
        run: |
          export resourceGroup=${GITHUB_RUN_ID}${GITHUB_RUN_NUMBER}
          echo ${resourceGroup} ${location}
          mvn -DsubscriptionId=${{ secrets.subscriptionId }} -DresourceGroup=${resourceGroup} -DappName=${resourceGroup} -Dregion=${location} --file helloworldfarm/noframework/pom.xml clean package azure-webapp:deploy

      - name: Assert correctness of noframework
        run: |
          export resourceGroup=${GITHUB_RUN_ID}${GITHUB_RUN_NUMBER}
          export testhost=${resourceGroup}.azurewebsites.net
          for i in {1..20}
          do
              echo "testing https://${testhost}/test"
              curl --verbose https://${testhost}/test > out.txt || true
              if grep "Hello World" out.txt
              then
                  echo "SUCCESS"
                  exit $?
              else
                  echo "FAILED. RETRY $i of 20."
                  sleep 5
              fi
          done
          exit 1
      
  cleanup-noframework:
    needs: noframework
    if: always()
    runs-on: ubuntu-latest
    steps:
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Delete Resource Group
        id: delete-resource-group
        run: |
          export resourceGroup=${GITHUB_RUN_ID}${GITHUB_RUN_NUMBER}
          echo ${resourceGroup} ${location}
          az group delete --yes --no-wait --verbose --name ${resourceGroup}
